checks:
  - name: lighthouse-keeper
    options:
      buildPath: ./dist
      # url: http://localhost:3000
      minScores:
        performance: 100
        accessibility: 100
        best-practices: 100
        seo: 100
        pwa: 10