name: PageSpeed-EVA
on: push

jobs:
  build-and-codechecks:
    name: Teste PageSpeed-EVA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Executando o build Ev-Front
        run: |
          yarn install --frozen-lockfile
          yarn build
          npx codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}