name: Teste PageSpeed
on: [push, pull_request]

name: Mainflow
jobs:
  build-and-codechecks:
    name: build and run codechecks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: yarn
        run: |
          yarn install --frozen-lockfile

          npx codechecks
        env:
          CC_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0U2VjcmV0IjoiZjczODMyNDQtNzExOS00NDBlLTkyYTAtMzM5NzYxMmY3NTQ2In0.PpQ2iK6tRUYZpdGdj07dMlGXq1YuefCLWbV3tllGLhA