on: push
name: Mainflow
jobs:
  build-and-codechecks:
    name: build and run codechecks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: yarn
        run: |
          yarn
          yarn build
          yarn codechecks