name: Cumprimentar a Todos
# Este fluxo de trabalho é acionado em pushes para o repositório.
on: [push, pull_request]

jobs:
  build:
    # o nome do trabalho é greeting (cumprimentar)
    name: Teste
    # Este trabalho executa no Linux
    runs-on: ubuntu-latest
    steps:
      # Esta etapa usa hello-world-javascript-action do GitHub: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/setup-node@v10
        run: |
        npm ci
        npm run build