name: Teste PageSpeed
# Este fluxo de trabalho é acionado em pushes para o repositório.
on: [push]

jobs:
  build:
    # o nome do trabalho é greeting (cumprimentar)
    name: Testando PageSpeed
    # Este trabalho executa no Linux
    runs-on: ubuntu-latest
    steps:
      # Esta etapa usa hello-world-javascript-action do GitHub: https://github.com/actions/hello-world-javascript-action
      - uses: actions/setup-node@v1
        with:
          author: ${{ github.actor }}
          install: yarn
          build: yarn build
          teste: yarn teste